# Generated by Django 3.2.7 on 2021-09-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created'], 'verbose_name_plural': 'Products'},
        ),
    ]
